YAKEcloud/yake

- pre-gardener/ingress-nginx.yaml
https://github.com/kubernetes/ingress-nginx/issues/10784
> Downgrade ingress-nginx to 4.8.3 as 4.8.4 was a broken release that got removed

- .github/workflows/build-and-push-provider-local.yaml
- .github/workflows/deploy-docs.yaml
- .github/workflows/release.yaml
- .github/workflows/yaml-syntax-check.yml
Since we're public now and github's runners are pwoerful enough, there's no point in using self-hosted runners.
> Switch to github runners where possible

- .github/workflows/release.yaml
Patch releases now work correctly when triggered by a push on `release-v*` branches
Parsing the version now doesn't break for multiline commit messages.
The github release now uses the parsed version number.
> Fix automatic patch releases on release branches

- gardener/extensions/templates/helmrelease-admission.yaml
The commit introduces the kustomize post-renderer in the Helm release admission template. It specifically adds a patch to replace the spec to automount the Service Account token. This modification ensures the Deployment kind 'gardener-extension-admission' has this token automatically mounted.
--
Various upstream extensions disable this property if a custom kubeconfig is set. This doesn't fit our use-case and may even be unintended in the first place. 
https://github.com/gardener/gardener-extension-provider-openstack/blob/4531784c98d2e6339bc94f296f56484bb83bfa37/charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml#L29
> Force-enable automountServiceAccountToken in extension admission controller helm releases

- configuration/configuration/templates/extensions.yaml
The admission controller is required for some of its features
> Enable admission for shoot-dns-service extension

- configuration/configuration/templates/extensions.yaml
Reverts YAKEcloud/yake#1399
We are missing netpols to make this admission work properly
> Revert "Enable admission for shoot-dns-service extension"

- configuration/configuration/templates/ingress-nginx.yaml
- configuration/configuration/tests/cert-manager_test.yaml
- configuration/configuration/tests/ingress-nginx_test.yaml
- gardener/networkpolicies/garden-kube-apiserver.yaml
- pre-gardener/networkpolicies/garden-ingress-nginx.yaml
Gardener's ingressClass `nginx-ingress-gardener` selects its pods using the `app: nginx-ingress` label. To prevent conflicts with our own ingress, we're moving away from these labels and use `yake.cloud/app: ingress-nginx` instead.
> Migrate ingress-nginx pod labels 

- gardener/networkpolicies/garden-gardener-dashboard.yaml
- gardener/networkpolicies/garden-gardener-metrics-exporter.yaml
- gardener/networkpolicies/garden-identity.yaml
Add network policies for dashboard, identity and gardener-metrics-exporter.
Changing our ingress-nginx's labels made these necessary. 
`garden-kube-apiserver` already has a suitable network policy.
> Allow ingress to talk to dashboard, identity and gardener-metrics-exporter

- configuration/configuration/templates/etcd.yaml
Make credentials secret match expected files:
https://github.com/gardener/etcd-backup-restore/blob/17e447b2fd4cb1291e415130f70fa4017f4cc7b7/pkg/snapstore/swift_snapstore.go#L239
> Fix etcd backup credentials for swift

- .github/renovate.json5
- configuration/configuration/templates/extensions.yaml
Renovate any dependency that is not yet detected by renovate by adding this magic comment:
`someProperty: v1.23.4 # renovate: datasource=<datasource> depName=<depName> versioning=<versioning>`
"versioning" is optional
> Add renovate regex pattern for all yaml files, track dns-controller-manager

- configuration/configuration/templates/etcd.yaml
- configuration/configuration/templates/velero.yaml
- gardener/garden-content/templates/secret-backup-internal-seed.yaml
https://github.com/metal-stack/gardener-extension-backup-s3 is required for shoot etcd-backups to work.
Unfortunately the current implementation leads to some duplicated values in the yake-config secret since backups.credentials is [passed into garden-content verbatim](https://github.com/YAKEcloud/yake/blob/b783f0d109b55404134b6e1034d046cab6614d97/configuration/configuration/templates/garden-content.yaml#L11)
We could make https://github.com/YAKEcloud/yake/blob/main/configuration/configuration/templates/etcd.yaml and https://github.com/YAKEcloud/yake/blob/main/configuration/configuration/templates/velero.yaml read the region from backups.credentials and document the breaking change. Since etcd/seedSpec expect these in base64 and velero doesn't there's always gonna be en- or decoding …
> Allow generic s3 endpoints for entire backup stack (etcd-0, velero, shoot-etcds)

- .github/workflows/build-and-push-provider-local.yaml
- hack/ci/yake-local/build-extension-provider-local.sh
- hack/ci/yake-local/update-extension-provider-local-image.sh
When renovate updates gardener-controlplane, the tests fail because the matching version of provider-local isn't available, yet.
This sets the release action to run on pushes to the respective branches. It also allows running the action manually.
The yake-local test run stalls until the image is available but the required 3 minutes should be well within timeouts.
Also adds a missing "v"-prefix on provider-local controller-registration updates.
> Release provider-local image on gardener-controlplane update PRs

- README.md
We've had a report about the ["too many open files" error](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files) which seems to be a common issue with kind clusters (or running larger clusters locally in general).
This should make people aware of possible issues with kind and how to solve them.
> Mention kind's "known issues" section in README

- gardener/extensions/templates/helmrelease-controller.yaml
Controllerdeployment v1 expects helmchart values under /helm/values, while legacy v1beta1 expects them under /providerConfig/values. This PR aims to support both.
> Apply specific values patches to extension controllerdeployment versions v1 and v1beta1

- configuration/configuration/templates/extensions.yaml
It comes with a default now, so we'll just let it use that.
> Don't pin shoot-dns-service's dns-controller-manager version

- .github/workflows/release.yaml
- hack/release/upload-oci.sh
- hack/tools/install.sh
To ease running YAKE in an air-gapped environment this reintroduces OCI image releases. 
Another job was added to the existing release workflow. If "prepare" succeeds, the image is built and pushed to ghcr.io/yakecloud/yake
Partially reverts #1222
> Publish OCI Image of YAKE

- .github/workflows/release.yaml
- hack/release/prepare.sh
Looking for the branch in .git/refs/heads/ only works if the branch was checked out before. Instead we'll use rev-parse on the remote branch name. It will produce false positives if a tag of the same name exists, but that seems like an acceptable risk here.
Also there was a copy&paste error in the workflow causing a "v" to be prepended to the make_latest boolean, making it an always truish string.
> Fix marking releases as latest

- .github/renovate.json
Renovate didn't match packages containing numbers (like backup-s3). Fixed the regex.
> Renovate: Match package names containing numbers

- pre-gardener/dnsprovider/templates/tests/dnsprovider.yaml
- pre-gardener/issuer/templates/tests/issuer.yaml
> Instead of bitnami/kubectl, use gardeners ops-toolbelt image

- configuration/configuration/templates/extensions.yaml
- gardener/extensions/templates/helmrelease-admission.yaml
* enable admission for alicloud by default
* azure has not release a true split version yet and needs the global.kubeconfig still
* remove all other values, tls secrets etc, this has not been required for a while already
* tested with all extensions where we enable admission by default
> Support "split" admission charts
